MONGO_CONNECTION_STRING = "mongodb+srv://luizbicalho:yAQi6qBMIvcay9KY@cluster0.deys5zq.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
AUTH_COOKIE_NAME = "luizbicalho"
AUTH_COOKIE_KEY = "yAQi6qBMIvcay9KY" # Gere uma string aleatória e segura
AUTH_COOKIE_EXPIRY_DAYS = 30