MONGO_CONNECTION_STRING = "mongodb+srv://luizbicalho:<db_password>@cluster0.deys5zq.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
AUTH_COOKIE_NAME = "simulador_auth_cookie"
AUTH_COOKIE_KEY = "d46a5s4d6a8s7d" # Gere uma string aleatória e segura
AUTH_COOKIE_EXPIRY_DAYS = 30