MONGO_CONNECTION_STRING = "mongodb+srv://luizbicalho:yAQi6qBMIvcay9KY@seucluster.mongodb.net/simulador_db?retryWrites=true&w=majority"
AUTH_COOKIE_NAME = "simulador_auth_cookie"
AUTH_COOKIE_KEY = "coloque_uma_chave_secreta_aleatoria_aqui" # Gere uma string aleatória e segura
AUTH_COOKIE_EXPIRY_DAYS = 30